import type { ComponentType } from "react";
import {
  CharacterCounter,
  ParagraphCounter,
  ReadingTime,
  SentenceCounter,
  SpeakingTime,
  WordCounter,
} from "./writing";
import {
  ExpandText,
  GrammarChecker,
  OutlineGenerator,
  RewriteTool,
  ShortenText,
  Summarizer,
  TextStatistics,
} from "./writing-extra";
import {
  CaseConverter,
  ExtractEmails,
  ExtractNumbers,
  ExtractUrls,
  FindReplace,
  LineSorter,
  PrefixSuffix,
  RemoveDuplicateLines,
  RemoveEmptyLines,
  ReverseText,
} from "./text-tools";
import { RemoveEmojis, RemoveSpecialCharacters } from "./text-extra";
import {
  ThumbnailTextChecker,
  YoutubeHookGenerator,
  YoutubeTagGenerator,
  YoutubeTitleGenerator,
} from "./youtube";
import {
  ChapterGenerator,
  CtaGenerator,
  CtrAnalyzer,
  ScriptTimer,
  ShortsIdeaGenerator,
  YoutubeDescriptionGenerator,
  YoutubeKeywordFinder,
} from "./youtube-extra";
import {
  KeywordDensity,
  MetaDescriptionGenerator,
  MetaTitleGenerator,
  SlugGenerator,
} from "./seo";
import {
  InternalLinkSuggestions,
  RobotsTxtGenerator,
  SerpPreview,
  SitemapGenerator,
} from "./seo-extra";
import { BioGenerator, HashtagGenerator } from "./social";
import {
  CaptionGenerator,
  EmojiPicker,
  InstagramCaptionOptimizer,
  LinkedinFormatter,
  ThreadGenerator,
  TweetFormatter,
} from "./social-extra";
import {
  AspectRatioCalculator,
  ImagePromptEnhancer,
  NegativePromptGenerator,
} from "./image";
import {
  ColorPaletteGenerator,
  PromptHistory,
  PromptRandomizer,
  PromptStyleLibrary,
} from "./image-extra";
import {
  Base64Encoder,
  JsonFormatter,
  UrlEncoder,
  UuidGenerator,
} from "./developer";
import {
  CssBeautifier,
  HtmlFormatter,
  JsonCompare,
  JsonValidator,
  JwtDecoder,
  RegexTester,
  SqlFormatter,
  XmlFormatter,
} from "./developer-extra";
import { AiCostCalculator, AiTokenCalculator } from "./ai";
import {
  AiChatExportCleaner,
  AiImagePromptBuilder,
  AiPromptShortener,
  AiPromptTester,
  AiPromptTranslator,
  PromptFormatter,
  PromptGenerator,
  PromptLibrary,
  PromptOptimizer,
} from "./ai-extra";
import {
  CompressPdf,
  ImageToPdf,
  MergePdf,
  OcrTool,
  PdfToWord,
  SplitPdf,
  WordToPdf,
} from "./pdf-tools";
import {
  AudioConverter,
  BulkRenamer,
  FileCompressor,
  ImageConverter,
  VideoConverter,
  ZipCompressor,
  ZipExtractor,
} from "./file-tools";
import {
  LoremIpsumGenerator,
  TextRepeater,
  TextToCsv,
  ColumnAligner,
  NumberToWords,
  PalindromeChecker,
  AnagramFinder,
  MorseCodeConverter,
  MarkdownPreview,
  PasswordGenerator,
  CharacterFrequencyCounter,
  WordFrequencyCounter,
} from "./text-more";
import {
  ReadingEaseChecker,
  HeadlineAnalyzer,
  BlogTitleGenerator,
  EssayTitleGenerator,
  RhymeFinder,
  SyllableCounter,
  HaikuGenerator,
  AcronymGenerator,
  ResignationLetterGenerator,
  ColdEmailGenerator,
  EmailSubjectGenerator,
  ThankYouNoteGenerator,
  ConclusionGenerator,
} from "./writing-more";
import {
  VideoIdeaGenerator,
  VideoOutlineGenerator,
  CommunityPostGenerator,
  ThumbnailTextGenerator,
  VideoChecklistGenerator,
  MetaKeywordsGenerator,
  HeadingOutlineGenerator,
  AltTextGenerator,
  ContentBriefGenerator,
  FaqSchemaGenerator,
} from "./seo-more";
import {
  TikTokIdeaGenerator,
  InstagramStoryGenerator,
  PinterestTitleGenerator,
  PollIdeasGenerator,
  ContentCalendarGenerator,
} from "./social-more";
import {
  LightingPromptGenerator,
  CameraSettingsGenerator,
  LoraPromptGenerator,
  PromptExtender,
} from "./image-more";
import {
  TimestampConverter,
  ColorConverter,
  JsonToCsv,
  CsvToJson,
  JsonToYaml,
  HtmlToMarkdown,
  HtmlEntityEncoder,
  RegexEscape,
  Sha256HashGenerator,
  RandomNumberGenerator,
  PasswordStrengthChecker,
  TextDiff,
} from "./developer-more";
import {
  InterviewQuestionGenerator,
  MidjourneyPromptGenerator,
  PromptComparator,
  AiResponseImprover,
  QuestionGenerator,
} from "./ai-more";

export const toolComponents: Record<string, ComponentType> = {
  "character-counter": CharacterCounter,
  "word-counter": WordCounter,
  "sentence-counter": SentenceCounter,
  "paragraph-counter": ParagraphCounter,
  "reading-time": ReadingTime,
  "speaking-time": SpeakingTime,
  "case-converter": CaseConverter,
  "find-and-replace": FindReplace,
  "remove-duplicate-lines": RemoveDuplicateLines,
  "remove-empty-lines": RemoveEmptyLines,
  "line-sorter": LineSorter,
  "prefix-suffix": PrefixSuffix,
  "reverse-text": ReverseText,
  "extract-urls": ExtractUrls,
  "extract-emails": ExtractEmails,
  "extract-numbers": ExtractNumbers,
  "youtube-title-generator": YoutubeTitleGenerator,
  "youtube-tag-generator": YoutubeTagGenerator,
  "youtube-hook-generator": YoutubeHookGenerator,
  "thumbnail-text-checker": ThumbnailTextChecker,
  "keyword-density": KeywordDensity,
  "meta-title-generator": MetaTitleGenerator,
  "meta-description-generator": MetaDescriptionGenerator,
  "slug-generator": SlugGenerator,
  "hashtag-generator": HashtagGenerator,
  "bio-generator": BioGenerator,
  "image-prompt-enhancer": ImagePromptEnhancer,
  "negative-prompt-generator": NegativePromptGenerator,
  "aspect-ratio-calculator": AspectRatioCalculator,
  "json-formatter": JsonFormatter,
  "base64-encoder": Base64Encoder,
  "url-encoder": UrlEncoder,
  "uuid-generator": UuidGenerator,
  "ai-token-calculator": AiTokenCalculator,
  "ai-cost-calculator": AiCostCalculator,
  "text-statistics": TextStatistics,
  "grammar-checker": GrammarChecker,
  "rewrite-tool": RewriteTool,
  "summarizer": Summarizer,
  "expand-text": ExpandText,
  "shorten-text": ShortenText,
  "outline-generator": OutlineGenerator,
  "remove-emojis": RemoveEmojis,
  "remove-special-characters": RemoveSpecialCharacters,
  "youtube-description-generator": YoutubeDescriptionGenerator,
  "ctr-analyzer": CtrAnalyzer,
  "script-timer": ScriptTimer,
  "shorts-idea-generator": ShortsIdeaGenerator,
  "cta-generator": CtaGenerator,
  "chapter-generator": ChapterGenerator,
  "youtube-keyword-finder": YoutubeKeywordFinder,
  "robots-txt-generator": RobotsTxtGenerator,
  "sitemap-generator": SitemapGenerator,
  "serp-preview": SerpPreview,
  "internal-link-suggestions": InternalLinkSuggestions,
  "caption-generator": CaptionGenerator,
  "tweet-formatter": TweetFormatter,
  "thread-generator": ThreadGenerator,
  "linkedin-formatter": LinkedinFormatter,
  "instagram-caption-optimizer": InstagramCaptionOptimizer,
  "emoji-picker": EmojiPicker,
  "prompt-style-library": PromptStyleLibrary,
  "color-palette-generator": ColorPaletteGenerator,
  "prompt-randomizer": PromptRandomizer,
  "prompt-history": PromptHistory,
  "json-validator": JsonValidator,
  "json-compare": JsonCompare,
  "xml-formatter": XmlFormatter,
  "html-formatter": HtmlFormatter,
  "css-beautifier": CssBeautifier,
  "sql-formatter": SqlFormatter,
  "regex-tester": RegexTester,
  "jwt-decoder": JwtDecoder,
  "prompt-formatter": PromptFormatter,
  "prompt-optimizer": PromptOptimizer,
  "prompt-generator": PromptGenerator,
  "prompt-library": PromptLibrary,
  "ai-prompt-tester": AiPromptTester,
  "ai-image-prompt-builder": AiImagePromptBuilder,
  "ai-chat-export-cleaner": AiChatExportCleaner,
  "ai-prompt-translator": AiPromptTranslator,
  "ai-prompt-shortener": AiPromptShortener,
  "pdf-merge": MergePdf,
  "pdf-split": SplitPdf,
  "pdf-compress": CompressPdf,
  "pdf-to-word": PdfToWord,
  "word-to-pdf": WordToPdf,
  "zip-compressor": ZipCompressor,
  "file-compressor": FileCompressor,
  "bulk-renamer": BulkRenamer,
  "image-converter": ImageConverter,
  "video-converter": VideoConverter,
  "audio-converter": AudioConverter,
  "zip-extractor": ZipExtractor,
  "image-to-pdf": ImageToPdf,
  "ocr": OcrTool,
  "readability-checker": ReadingEaseChecker,
  "headline-analyzer": HeadlineAnalyzer,
  "blog-title-generator": BlogTitleGenerator,
  "essay-title-generator": EssayTitleGenerator,
  "rhyme-finder": RhymeFinder,
  "syllable-counter": SyllableCounter,
  "haiku-generator": HaikuGenerator,
  "acronym-generator": AcronymGenerator,
  "resignation-letter-generator": ResignationLetterGenerator,
  "cold-email-generator": ColdEmailGenerator,
  "email-subject-generator": EmailSubjectGenerator,
  "thank-you-note-generator": ThankYouNoteGenerator,
  "conclusion-generator": ConclusionGenerator,
  "video-idea-generator": VideoIdeaGenerator,
  "video-outline-generator": VideoOutlineGenerator,
  "community-post-generator": CommunityPostGenerator,
  "thumbnail-text-generator": ThumbnailTextGenerator,
  "video-checklist-generator": VideoChecklistGenerator,
  "meta-keywords-generator": MetaKeywordsGenerator,
  "heading-outline-generator": HeadingOutlineGenerator,
  "alt-text-generator": AltTextGenerator,
  "content-brief-generator": ContentBriefGenerator,
  "faq-schema-generator": FaqSchemaGenerator,
  "tiktok-idea-generator": TikTokIdeaGenerator,
  "instagram-story-generator": InstagramStoryGenerator,
  "pinterest-title-generator": PinterestTitleGenerator,
  "poll-ideas-generator": PollIdeasGenerator,
  "content-calendar-generator": ContentCalendarGenerator,
  "lighting-prompt-generator": LightingPromptGenerator,
  "camera-settings-generator": CameraSettingsGenerator,
  "lora-prompt-generator": LoraPromptGenerator,
  "prompt-extender": PromptExtender,
  "lorem-ipsum-generator": LoremIpsumGenerator,
  "text-repeater": TextRepeater,
  "text-to-csv": TextToCsv,
  "column-aligner": ColumnAligner,
  "number-to-words": NumberToWords,
  "palindrome-checker": PalindromeChecker,
  "anagram-finder": AnagramFinder,
  "morse-code-converter": MorseCodeConverter,
  "markdown-preview": MarkdownPreview,
  "password-generator": PasswordGenerator,
  "character-frequency-counter": CharacterFrequencyCounter,
  "word-frequency-counter": WordFrequencyCounter,
  "timestamp-converter": TimestampConverter,
  "color-converter": ColorConverter,
  "json-to-csv": JsonToCsv,
  "csv-to-json": CsvToJson,
  "json-to-yaml": JsonToYaml,
  "html-to-markdown": HtmlToMarkdown,
  "html-entity-encoder": HtmlEntityEncoder,
  "regex-escape": RegexEscape,
  "sha256-generator": Sha256HashGenerator,
  "random-number-generator": RandomNumberGenerator,
  "password-strength-checker": PasswordStrengthChecker,
  "text-diff": TextDiff,
  "interview-question-generator": InterviewQuestionGenerator,
  "midjourney-prompt-generator": MidjourneyPromptGenerator,
  "prompt-comparator": PromptComparator,
  "ai-response-improver": AiResponseImprover,
  "question-generator": QuestionGenerator,
};
