import type { ComponentType } from "react";
import {
  CharacterCounter,
  ParagraphCounter,
  ReadingTime,
  SentenceCounter,
  SpeakingTime,
  WordCounter,
} from "./writing";
import {
  ExpandText,
  GrammarChecker,
  OutlineGenerator,
  RewriteTool,
  ShortenText,
  Summarizer,
  TextStatistics,
} from "./writing-extra";
import {
  CaseConverter,
  ExtractEmails,
  ExtractNumbers,
  ExtractUrls,
  FindReplace,
  LineSorter,
  PrefixSuffix,
  RemoveDuplicateLines,
  RemoveEmptyLines,
  ReverseText,
} from "./text-tools";
import { RemoveEmojis, RemoveSpecialCharacters } from "./text-extra";
import {
  ThumbnailTextChecker,
  YoutubeHookGenerator,
  YoutubeTagGenerator,
  YoutubeTitleGenerator,
} from "./youtube";
import {
  ChapterGenerator,
  CtaGenerator,
  CtrAnalyzer,
  ScriptTimer,
  ShortsIdeaGenerator,
  YoutubeDescriptionGenerator,
  YoutubeKeywordFinder,
} from "./youtube-extra";
import {
  KeywordDensity,
  MetaDescriptionGenerator,
  MetaTitleGenerator,
  SlugGenerator,
} from "./seo";
import {
  InternalLinkSuggestions,
  RobotsTxtGenerator,
  SerpPreview,
  SitemapGenerator,
} from "./seo-extra";
import { BioGenerator, HashtagGenerator } from "./social";
import {
  CaptionGenerator,
  EmojiPicker,
  InstagramCaptionOptimizer,
  LinkedinFormatter,
  ThreadGenerator,
  TweetFormatter,
} from "./social-extra";
import {
  AspectRatioCalculator,
  ImagePromptEnhancer,
  NegativePromptGenerator,
} from "./image";
import {
  ColorPaletteGenerator,
  PromptHistory,
  PromptRandomizer,
  PromptStyleLibrary,
} from "./image-extra";
import {
  Base64Encoder,
  JsonFormatter,
  UrlEncoder,
  UuidGenerator,
} from "./developer";
import {
  CssBeautifier,
  HtmlFormatter,
  JsonCompare,
  JsonValidator,
  JwtDecoder,
  RegexTester,
  SqlFormatter,
  XmlFormatter,
} from "./developer-extra";
import { AiCostCalculator, AiTokenCalculator } from "./ai";
import {
  AiChatExportCleaner,
  AiImagePromptBuilder,
  AiPromptShortener,
  AiPromptTester,
  AiPromptTranslator,
  PromptFormatter,
  PromptGenerator,
  PromptLibrary,
  PromptOptimizer,
} from "./ai-extra";

export const toolComponents: Record<string, ComponentType> = {
  "character-counter": CharacterCounter,
  "word-counter": WordCounter,
  "sentence-counter": SentenceCounter,
  "paragraph-counter": ParagraphCounter,
  "reading-time": ReadingTime,
  "speaking-time": SpeakingTime,
  "case-converter": CaseConverter,
  "find-and-replace": FindReplace,
  "remove-duplicate-lines": RemoveDuplicateLines,
  "remove-empty-lines": RemoveEmptyLines,
  "line-sorter": LineSorter,
  "prefix-suffix": PrefixSuffix,
  "reverse-text": ReverseText,
  "extract-urls": ExtractUrls,
  "extract-emails": ExtractEmails,
  "extract-numbers": ExtractNumbers,
  "youtube-title-generator": YoutubeTitleGenerator,
  "youtube-tag-generator": YoutubeTagGenerator,
  "youtube-hook-generator": YoutubeHookGenerator,
  "thumbnail-text-checker": ThumbnailTextChecker,
  "keyword-density": KeywordDensity,
  "meta-title-generator": MetaTitleGenerator,
  "meta-description-generator": MetaDescriptionGenerator,
  "slug-generator": SlugGenerator,
  "hashtag-generator": HashtagGenerator,
  "bio-generator": BioGenerator,
  "image-prompt-enhancer": ImagePromptEnhancer,
  "negative-prompt-generator": NegativePromptGenerator,
  "aspect-ratio-calculator": AspectRatioCalculator,
  "json-formatter": JsonFormatter,
  "base64-encoder": Base64Encoder,
  "url-encoder": UrlEncoder,
  "uuid-generator": UuidGenerator,
  "ai-token-calculator": AiTokenCalculator,
  "ai-cost-calculator": AiCostCalculator,
  "text-statistics": TextStatistics,
  "grammar-checker": GrammarChecker,
  "rewrite-tool": RewriteTool,
  "summarizer": Summarizer,
  "expand-text": ExpandText,
  "shorten-text": ShortenText,
  "outline-generator": OutlineGenerator,
  "remove-emojis": RemoveEmojis,
  "remove-special-characters": RemoveSpecialCharacters,
  "youtube-description-generator": YoutubeDescriptionGenerator,
  "ctr-analyzer": CtrAnalyzer,
  "script-timer": ScriptTimer,
  "shorts-idea-generator": ShortsIdeaGenerator,
  "cta-generator": CtaGenerator,
  "chapter-generator": ChapterGenerator,
  "youtube-keyword-finder": YoutubeKeywordFinder,
  "robots-txt-generator": RobotsTxtGenerator,
  "sitemap-generator": SitemapGenerator,
  "serp-preview": SerpPreview,
  "internal-link-suggestions": InternalLinkSuggestions,
  "caption-generator": CaptionGenerator,
  "tweet-formatter": TweetFormatter,
  "thread-generator": ThreadGenerator,
  "linkedin-formatter": LinkedinFormatter,
  "instagram-caption-optimizer": InstagramCaptionOptimizer,
  "emoji-picker": EmojiPicker,
  "prompt-style-library": PromptStyleLibrary,
  "color-palette-generator": ColorPaletteGenerator,
  "prompt-randomizer": PromptRandomizer,
  "prompt-history": PromptHistory,
  "json-validator": JsonValidator,
  "json-compare": JsonCompare,
  "xml-formatter": XmlFormatter,
  "html-formatter": HtmlFormatter,
  "css-beautifier": CssBeautifier,
  "sql-formatter": SqlFormatter,
  "regex-tester": RegexTester,
  "jwt-decoder": JwtDecoder,
  "prompt-formatter": PromptFormatter,
  "prompt-optimizer": PromptOptimizer,
  "prompt-generator": PromptGenerator,
  "prompt-library": PromptLibrary,
  "ai-prompt-tester": AiPromptTester,
  "ai-image-prompt-builder": AiImagePromptBuilder,
  "ai-chat-export-cleaner": AiChatExportCleaner,
  "ai-prompt-translator": AiPromptTranslator,
  "ai-prompt-shortener": AiPromptShortener,
};
